CREATE DATABASE db_previred
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE TABLE IF NOT EXISTS public.empresas
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha timestamp without time zone NOT NULL,
    identificador character varying(255) COLLATE pg_catalog."default",
    razon_social character varying(255) COLLATE pg_catalog."default",
    rut character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT empresas_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.empresas
    OWNER to "user";


CREATE TABLE IF NOT EXISTS public.trabajadores
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    apellido_materno character varying(255) COLLATE pg_catalog."default",
    apellido_paterno character varying(255) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    rut character varying(255) COLLATE pg_catalog."default",
    empresa_id bigint,
    CONSTRAINT trabajadores_pkey PRIMARY KEY (id),
    CONSTRAINT fkjjjbdr4kuhrdiq5houakgb0pe FOREIGN KEY (empresa_id)
        REFERENCES public.empresas (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.trabajadores
    OWNER to "user";